apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wso2
  name: endpoints-reader-role
rules:
- apiGroups: [""]
  verbs: ["get", "list"]
  resources: ["endpoints"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: wso2-endpoints-reader-role-binding
  namespace: wso2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoints-reader-role
subjects:
  - kind: ServiceAccount
    name: wso2svc-account
    namespace: wso2
